💤 Putting to bed

diff --git a/link-add b/link-add
--- a/link-add
+++ b/link-add
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 set -e
 
-which jq >/dev/null 2>&1 || { echo >&2 "💥 jq is required but not installed!"; exit 1; }
+which jq >/dev/null 2>&1 || {
+  echo >&2 "💥 jq is required but not installed!"
+  exit 1
+}
 
 configFile="staticwebapp.config.json"
 
@@ -23,13 +26,13 @@ if [ -n "$(jq -r ".routes[] | select(.route == \"/$name\")" "$configFile")" ]; t
   exit 1
 fi
 
-jq ".routes += [{\"route\": \"/${name}\", \"redirect\": \"${url}\"}]" $configFile > $configFile.tmp && mv $configFile.tmp $configFile
+jq ".routes += [{\"route\": \"/${name}\", \"redirect\": \"${url}\"}]" $configFile >$configFile.tmp && mv $configFile.tmp $configFile
 
 echo -e "\e[34m»»» 🌐 Short link added: \e[33m$name \e[0m-> \e[32m$url"
 echo -e "\e[34m»»» ⌚ Wait approx 1 minute for the link to be active\e[0m"
 
-git add $configFile > /dev/null 2>&1
-git commit -m "Added link $name -> $url" > /dev/null 2>&1
-git push > /dev/null 2>&1
+git add $configFile >/dev/null 2>&1
+git commit -m "Added link $name -> $url" >/dev/null 2>&1
+git push >/dev/null 2>&1
 
-swa deploy --no-use-keychain --env production > /dev/null 2>&1
+swa deploy --no-use-keychain --env production >/dev/null 2>&1
